H-Reservation/Controllers/SystemSettingsController.cs
using H_application.DTOs.SystemSettingsDto;
using H_application.Service;
using Microsoft.AspNetCore.Mvc;

namespace H_Reservation.Controllers
{
    public class SystemSettingsController : Controller
    {
        private readonly ISystemSettingsService _systemSetting;

        public SystemSettingsController(ISystemSettingsService systemSetting)
        {
            _systemSetting = systemSetting;
        }

        public async Task<IActionResult> Index()
        {
            var result = await _systemSetting.GetAllSystemSetting(default);
            return View("Index", result);
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View("Create");
        }
        [HttpPost]
        public async Task<IActionResult> Store(SystemSettingsDtoCreate dto)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View("Create", dto);
                }
                var result = await _systemSetting.CreateSetting(dto);
                if (result)
                {
                    return RedirectToAction("Index");
                }

                // Add this:
                ModelState.AddModelError("Key", "This key already exists. Please use another key.");
                return View("Create", dto);

            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Unknow", ex.Message);
                return View("Create", dto);
            }
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int Id)
        {
            var get = await _systemSetting.GetSystemSettingById(Id);

            if (get == null)
                return NotFound();

            return View("Edit", get);

        }
        [HttpPost]
        public async Task<IActionResult> Update(SystemSettingsDtoUpdate dto)
        {
            if (!ModelState.IsValid)
            {
                return View("Edit");
            }
            var result = await _systemSetting.UpdateSetting(dto);
            if (result)
            {
                return RedirectToAction("Index");
            }
            return View("Edit", dto);
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int Id)
        {
            var get = await _systemSetting.GetSystemSettingById(Id);

            if (get == null)
                return NotFound();

            return View("Delete", get);

        }
        [HttpPost]
        public async Task<IActionResult> Destroy(SystemSettingsDtoUpdate dto)
        {
            if (!ModelState.IsValid)
            {
                return View("Delete");
            }
            var result = await _systemSetting.DeleteSetting(dto);
            if (result)
            {
                return RedirectToAction("Index");
            }
            return View("Delete", dto);
        }
    }
}

H-Reservation/Views/SystemSettings/Create.cshtml
@using H_application.DTOs.SystemSettingsDto
@model SystemSettingsDtoCreate

@{
    ViewData["Title"] = "System Setting";
}
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Add new System Setting Information</h4>
        <form asp-controller="SystemSettings" asp-action="Store" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div>
                <label asp-for="IsActive" class="control-label">IsActive</label>
                <input type="checkbox" asp-for="IsActive" class="form-check-input ml-2" />
                </div>
            <div class="form-row">
                <div class="form-group col-sm-4">
                    <span asp-validation-for="Key" class="text-danger"></span>
                    <label asp-for="Key" class="control-label">Key Setting</label>
                    <input asp-for="Key" type="text" placeholder="Key Setting" class="form-control " />

                </div>
                <div class="form-group col-sm-4">
                    <span asp-validation-for="Value" class="text-danger"></span>
                    <label asp-for="Value" class="control-label">Value Setting</label>
                    <input asp-for="Value" type="text" placeholder="Value Setting" class="form-control" />
                </div>
                <div class="form-group col-sm-4">
                    <span asp-validation-for="Category" class="text-danger"></span>
                    <label asp-for="Category" class="control-label">Category</label>
                    <input asp-for="Category" type="text" placeholder="Category" class="form-control" />
                </div>

            </div>
            <div class="form-row">

                <span asp-validation-for="Description" class="text-danger"></span>
                <label asp-for="Description" class="control-label">Description</label>
                <input asp-for="Description" type="text" placeholder="Description" class="form-control" />

               
            </div>

            <div class="form-group float-right mt-2">
                <button type="submit" class="btn btn-sm btn-success ml-1">Save</button>
                <a asp-action="Index" class="btn btn-sm btn-danger">Cancel</a>
            </div>
        </form>
    </div>

</div>

H-Reservation/Views/SystemSettings/Delete.cshtml
@using H_application.DTOs.SystemSettingsDto
@model SystemSettingsDtoUpdate

@{
    ViewData["Title"] = "System Setting";
}
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Delete System Setting Information</h4>
        <form asp-controller="SystemSettings" asp-action="Destroy" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="SettingId" />
            <div>
                <label asp-for="IsActive" class="control-label">IsActive</label>
                <input type="checkbox" asp-for="IsActive" class="form-check-input ml-2" />
            </div>
            <div class="form-row">
                <div class="form-group col-sm-4">
                    <span asp-validation-for="Key" class="text-danger"></span>
                    <label asp-for="Key" class="control-label">Key Setting</label>
                    <input asp-for="Key" type="text" placeholder="Key Setting" class="form-control " />

                </div>
                <div class="form-group col-sm-4">
                    <span asp-validation-for="Value" class="text-danger"></span>
                    <label asp-for="Value" class="control-label">Value Setting</label>
                    <input asp-for="Value" type="text" placeholder="Value Setting" class="form-control" />
                </div>
                <div class="form-group col-sm-4">
                    <span asp-validation-for="Category" class="text-danger"></span>
                    <label asp-for="Category" class="control-label">Category</label>
                    <input asp-for="Category" type="text" placeholder="Category" class="form-control" />
                </div>

            </div>
            <div class="form-row">

                <span asp-validation-for="Description" class="text-danger"></span>
                <label asp-for="Description" class="control-label">Description</label>
                <input asp-for="Description" type="text" placeholder="Description" class="form-control" />


            </div>

            <div class="form-group float-right mt-2">
                <button type="submit" class="btn btn-sm btn-success ml-1">Delete</button>
                <a asp-action="Index" class="btn btn-sm btn-danger">Cancel</a>
            </div>
        </form>
    </div>

</div>

H-Reservation/Views/SystemSettings/Edit.cshtml
@using H_application.DTOs.SystemSettingsDto
@model SystemSettingsDtoUpdate

@{
    ViewData["Title"] = "System Setting";
}
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Update System Setting Information</h4>
        <form asp-controller="SystemSettings" asp-action="Update" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="SettingId" />
            <div>
                <label asp-for="IsActive" class="control-label">IsActive</label>
                <input type="checkbox" asp-for="IsActive" class="form-check-input ml-2" />
            </div>
            <div class="form-row">
                <div class="form-group col-sm-4">
                    <span asp-validation-for="Key" class="text-danger"></span>
                    <label asp-for="Key" class="control-label">Key Setting</label>
                    <input asp-for="Key" type="text" placeholder="Key Setting" class="form-control " />

                </div>
                <div class="form-group col-sm-4">
                    <span asp-validation-for="Value" class="text-danger"></span>
                    <label asp-for="Value" class="control-label">Value Setting</label>
                    <input asp-for="Value" type="text" placeholder="Value Setting" class="form-control" />
                </div>
                <div class="form-group col-sm-4">
                    <span asp-validation-for="Category" class="text-danger"></span>
                    <label asp-for="Category" class="control-label">Category</label>
                    <input asp-for="Category" type="text" placeholder="Category" class="form-control" />
                </div>

            </div>
            <div class="form-row">

                <span asp-validation-for="Description" class="text-danger"></span>
                <label asp-for="Description" class="control-label">Description</label>
                <input asp-for="Description" type="text" placeholder="Description" class="form-control" />


            </div>

            <div class="form-group float-right mt-2">
                <button type="submit" class="btn btn-sm btn-success ml-1">Save Change</button>
                <a asp-action="Index" class="btn btn-sm btn-danger">Cancel</a>
            </div>
        </form>
    </div>

</div>

H-Reservation/Views/SystemSettings/Index.cshtml
@using H_application.DTOs.SystemSettingsDto
@model IEnumerable<SystemSettingsResponse>
<partial name="_style" />
<div class="card">
    <div class="card-body">
        <h4 class="card-title">SystemSetting Information</h4>
        <a asp-action="Create" class="btn btn-sm btn-success mt-2 mb-2"><i class="fa-solid fa-square-plus"></i></a>
        <div class="table-responsive">
            <table class="table table-stripped table-hover  zero-configuration">
                <thead>
                    <tr>

                        <th>
                          Key
                        </th>
                        <th>
                            Value
                        </th>
                        <th>
                            Category
                        </th>
                        <th>
                            IsActive
                        </th>
                        <th>
                            Description
                        </th>
                        <th>
                            Action
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>

                            <td>
                                @Html.DisplayFor(items => item.Key)
                            </td>

                            <td>
                                @Html.DisplayFor(items => item.Value)
                            </td>
                            <td>
                                @Html.DisplayFor(items => item.Category)
                            </td>
                            <td>
                                @if (item.IsActive == true)
                                {
                                    <span style="color: green; font-weight: bold;">Active</span>
                                }
                                else
                                {
                                    <span style="color: red; font-weight: bold;">Inactive</span>
                                }
                            </td>

                            <td>
                                @Html.DisplayFor(items => item.Description)
                            </td>
                            <td>
                                <a asp-controller="SystemSettings" asp-action="Edit" asp-route-Id="@item.SettingId" class="btn btn-sm btn-outline-primary mr-1">
                                    <i class="fa-solid fa-pen-nib"></i>
                                </a>
                                <a asp-controller="SystemSettings" asp-action="Delete" asp-route-Id="@item.SettingId" class="btn btn-sm btn-outline-danger">
                                    <i class="fa-solid fa-trash"></i>
                                </a>
                            </td>


                        </tr>
                    }

                </tbody>
            </table>
        </div>
    </div>
</div>